astring="Hello World!!"
print(astring)
print(len(astring))
print(astring.index("H"))
print(astring.count("l"))
print(astring[3:7])
print(astring[3:7:1])
print(astring[3:7:2])
print(astring[::-1])
print(astring.upper())
print(astring.lower())
print(astring.startswith("He"))
print(astring.endswith("asssdff"))
afewwords=astring.split(" ")
print(afewwords)
print(afewwords[0],"and", afewwords[1])